commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("category_page", views.category_page, name="category_page"),
    path("category_contents/<int:category_id>", views.category_contents, name="category_contents"),
    path("listing/<int:listing_id>", views.listing_page, name="listing_page"),
    path("watchlist", views.watchlist, name="watchlist"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Model to represent users"""
    watching = models.ManyToManyField("Listing", related_name="watchers")


class Category(models.Model):
    """This model represents different categories of items"""
    category_name = models.CharField(max_length=64)

    def __str__(self):
        return self.category_name


class Listing(models.Model):
    """This model represents the auction listings"""
    title = models.CharField(max_length=64)
    description = models.TextField()
    current_price = models.DecimalField(max_digits=6, decimal_places=2)  # reference: https://stackoverflow.com/questions/1139393/what-is-the-best-django-model-field-to-use-to-represent-a-us-dollar-amount
    is_active = models.BooleanField(default=True)
    picture = models.URLField(null=True, blank=True)
    picture_text = models.CharField(blank=True, default="", max_length=64)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="listings")
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    closed = models.BooleanField(default=False)


class Bid(models.Model):
    """This model creates the fields required for bidding"""
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")

    def __str__(self):
        return str(self.amount)


class Comment(models.Model):
    """This model creates fields required for commenting on listings"""
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    text_comment = models.TextField(max_length=128)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.forms import ModelForm


from .models import Bid, User, Listing, Category, Comment


class CreateNewListing(ModelForm):
    class Meta:
        model = Listing
        fields = ["title", "description", "current_price", "picture", "picture_text", "category"]


class CreateNewComment(ModelForm):
    class Meta:
        model = Comment
        fields = ["text_comment"]


class CreateBid(ModelForm):
    class Meta:
        model = Bid
        fields = ["amount"]


def index(request):
    """This function renders the index page and provides the listings database"""
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all()
    })


def login_view(request):
    """When a user tries to GET the page, this view renders a login form.
    When a form is sumbitted using POST, the user
    is authenticated, signed in, and brought to the home page."""
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    """This view logs out the user and then returns to the index page"""
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    """This view renders a registration form, and creates a new user
    when the form is submitted. """
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


def create_listing(request):
    """This view renders the create listing form. If the request method
     is POST the sumbited data is saved to the listing database and the user
     is redirected to the index page."""
    if request.method == "POST":
        form = CreateNewListing(request.POST)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.seller = request.user   # The user is included as the seller
            listing.save()
            return HttpResponseRedirect(reverse("index"))

    form = CreateNewListing()
    return render(request, "auctions/create_listing.html", {
        "form": form,
    })


def listing_page(request, listing_id):
    """This view renders a page for each auction listing"""
    # retrieves listing by id
    listing_page = Listing.objects.get(id=listing_id)
    form = CreateNewComment()
    bid_form = CreateBid()

    # sets the starting bid as the first bid object
    
    if listing_page.bids.all():
        pass
    else:
        starter_bid = Bid(amount = listing_page.current_price, listing = listing_page, bidder = request.user )
        starter_bid.save()
    last_bids = listing_page.bids.last()


    # reference for including multiple forms in a view:
    # https://stackoverflow.com/questions/866272/how-can-i-build-multiple-submit-buttons-django-form
    if request.method == "POST" and 'create_comment' in request.POST:
        form = CreateNewComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            # includes addition data to save comment
            comment.author = request.user      
            comment.listing = listing_page
            comment.save()
            return HttpResponseRedirect(reverse("listing_page", kwargs={"listing_id": listing_id}))

    if request.method == "POST" and 'add_watchlist' in request.POST:
        # adds the listing to the user's watchlist
        listing_page.watchers.add(request.user)
        listing_page.save()

    if request.method == "POST" and 'remove_watchlist' in request.POST:
        # removes the listing to the user's watchlist
        current_user = request.user
        current_user.watching.remove(listing_page)

    if request.method == "POST" and 'place_bid' in request.POST:
        form = CreateBid(request.POST)
        if form.is_valid():
            new_bid = form.save(commit=False)
            # includes additional data to save comment
            new_bid.bidder = request.user      
            new_bid.listing = listing_page
            new_bid.save()
            return HttpResponseRedirect(reverse("listing_page", kwargs={"listing_id": listing_id}))
    
    if request.method == "POST" and 'close_page' in request.POST:
        # removes the listing to the user's watchlist
        listing_page.closed = True
        listing_page.save()

    return render(request, "auctions/listing_page.html", {
        "current_user": request.user,
        "watchers": listing_page.watchers.all(),
        "form": form,
        "bid_form": bid_form,
        "listing": listing_page,
        "comment": listing_page.comments.all(),
        "last_bids": last_bids,
        # the last bid is used to set a minimum value required in the CreateBid Field
        "lower_bound": round((float(last_bids.amount) + (0.01)), 2)
    })


def category_page(request):
    """This view renders a page that displays links 
    for different item categories"""
    categories = Category.objects.all()
    return render(request, "auctions/category_page.html", {
        "categories": categories,
    })


def category_contents(request, category_id):
    """This view renders the pages for items within a category, and provides
    the page with all the listings in a given category"""
    category_content = Category.objects.get(id=category_id)   
    category_listings = category_content.listings.all()
    return render(request, "auctions/category_contents.html", {
        "category_content": category_content,
        "category_listings": category_listings
    })


def watchlist(request):
    """This view renders a page where users can see what items are on their
    watchlist"""
    current_user = User.objects.get(username=request.user)
    return render(request, "auctions/watchlist.html", {
        "watchlist": current_user.watching.all()
    })

commerce/auctions/templates/auctions/category_contents.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% for listing in category_listings%}
    {% if listing.is_active %}
    <div class = "active_listing">  
        <a href="{% url 'listing_page' listing.id %}"><h4>{{listing.title}}</h4></a>
        <h6>Seller: {{listing.seller}}</h6>
        <p>{{listing.description}}</p>
        {% if listing.bids.last.amount %}
            <p>${{listing.bids.last.amount}}</p>
        {% else %}
            <p>{{listing.current_price}}</p>
        {% endif %}
        <img src="{{listing.picture}}" alt="{{listing.picture_text}}">
    </div>
    {% endif %}
    {% endfor %}
{% endblock %}

commerce/auctions/templates/auctions/category_page.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    {% for category in categories%}
    <div class = "categories">
       <ul>
        <li>
            <a href="{% url 'category_contents' category.id %}"><h4>{{category.category_name}}</h4></a>
         </li>
       </ul>
    </div>
    {% endfor %}
{% endblock %}

commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<form action="{% url 'create_listing'%}" method = "POST" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value = "Create Listing">
</form>
    
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    {% for listing in listings%}
        {% if listing.is_active %}
        <div class = "active_listing">  
            <a href="{% url 'listing_page' listing.id %}"><h4>{{listing.title}}</h4></a>
            <h6>Seller: {{listing.seller}}</h6>
            <p>{{listing.description}}</p>
            {% if listing.bids.last.amount %}
                <p>${{listing.bids.last.amount}}</p>
            {% else %}
                <p>{{listing.current_price}}</p>
            {% endif %}
            <img src="{{listing.picture}}" alt="{{listing.picture_text}}">
        </div>
        {% endif %}
    {% endfor %}
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400&display=swap" rel="stylesheet">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category_page' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">My Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/listing_page.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% if user.is_authenticated %}
        {% if current_user == listing.seller%}
            {% if listing.closed == False %}
            <form action="{% url 'listing_page' listing.id %}" method="post">
                {% csrf_token %}
                <button name="close_page" value="Close this page">Close this page</button>
            </form>
            {% endif %}
        {% else %}
            {% if  current_user not in watchers %}
                <form action="{% url 'listing_page' listing.id %}" method="post">
                    {% csrf_token %}
                    <button name="add_watchlist" value="Add to Watchlist">Add to Watchlist</button>
                </form>
            {% else %}
                <form action="{% url 'listing_page' listing.id %}" method="post">
                    {% csrf_token %}
                    <button name="remove_watchlist" value="Remove from Watchlist">Remove from Watchlist</button>
                </form>
            {% endif %}
        {% endif %}
    {% endif %}


<div class = "listing_page">
    {% if listing.closed == True %} 
        {% if current_user == last_bids.bidder %}
            {% if  last_bids.bidder != listing.seller%}
            <h4 class = "closed_message">You've won the auction for this item!</h4>
            {% else %}
            <h4 class = "closed_message">Listing is closed</h4>
            {% endif %}
        {% else %}
            <h4 class = "closed_message">Listing is closed</h4>
        {% endif %}
    {% endif %}
    <h4>{{listing.title}}</h4>
    <h6>Seller: {{listing.seller}}</h6>
    <p>{{listing.description}}</p>
    <img src="{{listing.picture}}" alt="{{listing.picture_text}}">
    {% if last_bids is none%}
        <p>Current Bid: ${{listing.current_price}}</p>
    {% else %}
        <p>Current Bid: ${{last_bids.amount}}</p>
    {% endif %}
    
    {% if user.is_authenticated %}
        {% if current_user != listing.seller %}
            {% if listing.closed == False %}
                <form class = "bid_form" action="{% url 'listing_page' listing.id %}" method = "POST">
                    {% csrf_token %}
                    {% comment %} reference for custom validation messages:
                    https://stackoverflow.com/questions/5272433/html5-form-required-attribute-set-custom-validation-message 
                    {% endcomment %}

                    {% comment %} I had trouble figuring out how to throw an error for bids that are too low —
                    I was able to access the min value attribute of the input by inspecting how {{bid_form}} rendered 
                    in my browser and included this input tag below {% endcomment %}
                    <input type="number" name="amount" min = "{{lower_bound}}" step="0.01" required="" id="id_amount" oninvalid="this.setCustomValidity('Must be higher')" oninput="this.setCustomValidity('')"/>
                    <input class = "bid_button" type="submit" name = "place_bid" value = "Place a Bid"  >
                </form>
            {% endif %}
        {% endif %}
    {% endif %}
</div>

{% if user.is_authenticated %}
    <form action="{% url 'listing_page' listing.id %}" method = "POST" >
        {% csrf_token %}
        {{form}}
        <input type="submit" name = "create_comment" value = "Create Comment">
    </form>
{% endif %}

{% for posting in comment%}
    <div class = "comment_block">
        <h6>Account: {{posting.author}}</h6>
        <p>{{posting.text_comment}}</p>
    </div>
{% endfor %}
    
{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Watchlist</h2>
    {% for listing in watchlist%}
        {% if listing.is_active %}
        <div class = "active_listing">  
            <a href="{% url 'listing_page' listing.id %}"><h4>{{listing.title}}</h4></a>
            <h6>Seller: {{listing.seller}}</h6>
            <p>{{listing.description}}</p>
            {% if listing.bids.last.amount %}
                <p>${{listing.bids.last.amount}}</p>
            {% else %}
                <p>{{listing.current_price}}</p>
            {% endif %}
            <img src="{{listing.picture}}" alt="{{listing.picture_text}}">
        </div>
        {% endif %}
    {% endfor %}
{% endblock %}